---
abstract: "Train on detecting successful Sudoku stategies.\nAlso help to get over an obstacle while solving a Sudoku puzzle."
author:
  - 'Klaus Wittrock <Wittrock@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SudokuTrainer
provides:
  Games::Sudoku::Trainer::GUI:
    file: lib/Games/Sudoku/Trainer/GUIdetails.pm
    version: 0
  Games::Sudoku::Trainer::GUIdetails:
    file: lib/Games/Sudoku/Trainer/GUIdetails.pm
    version: 0
  Games::Sudoku::Trainer::Run:
    file: lib/Games/Sudoku/Trainer/Run.pm
    version: v0.0.2
requires:
  Encode: 0
  List::MoreUtils: 0
  Tk: 0
  perl: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.00_08
